# Generated by Django 4.2.5 on 2023-10-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_imov_ufc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartments',
            new_name='Apartment',
        ),
    ]
