# Generated by Django 4.2.7 on 2023-12-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imov_ufc', '0002_rename_apartments_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='avaliacao',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='quant_curtidas',
            field=models.IntegerField(default=0),
        ),
    ]
